"""
installer.py — Sets up Claude Code integration for a project

Creates:
  - CLAUDE.md with the verification protocol
  - .claude/commands/verify.md slash command
  - .epistemix/ directory (gitignored)
  - Updates .gitignore
"""

import json
import shutil
from pathlib import Path


CLAUDE_MD_TEMPLATE = """\
# Epistemix: Epistemic verification protocol

> Generated by epistemix. Do not remove — this protocol prevents costly mistakes.

## ⚠️ MANDATORY before any implementation

Run the VERIFY protocol before writing any code.
This applies to every task, however simple it seems.

---

## VERIFY protocol

### Step 1 — Extract claims from the task

Read the task. List every implicit assumption you must have right to implement correctly.

```
CLAIMS:
- [term] I understand as: [your interpretation]
- [term] I understand as: [your interpretation]
```

### Step 2 — Find evidence in the codebase

For each claim, use your tools to find proof:
- Use **Grep** to search for the term across the project
- Use **Read** to open files where the term appears
- Use **Glob** to find related files

Check `.epistemix/context.md` first — it may already contain verified priors from previous sessions.

Classify each claim:
- **CERTAIN** — found unambiguous evidence (cite file:line)
- **UNCERTAIN** — found two or more conflicting interpretations
- **MISSING** — no trace in the codebase at all

### Step 3 — Answer auto-generated verification questions

If `.epistemix/context.md` contains verification questions, answer each one with a specific `file:line` reference before proceeding. These questions have objective answers in the code.

### Step 4 — Present your analysis

Use exactly this format:

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EPISTEMIC ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✅ CERTAIN (no confirmation needed):
- [term]: [interpretation]
  Evidence: [file:line]

⚠️ UNCERTAIN (please confirm):
- [term]: I understand this as [interpretation A]
  Alternative: [interpretation B]
  Found in: [file:line]

🚫 MISSING FROM CODEBASE:
- [what's missing] — critical because [why]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Is my understanding correct?
Please correct what's wrong and fill in missing info.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

### Step 5 — Wait for confirmation

**DO NOT start implementation** until the user confirms or corrects your analysis.

### Step 6 — Save verified assumptions

After confirmation, append to `.epistemix/session.md`:

```markdown
## Session [timestamp]
### Task: [task]
### Confirmed assumptions:
- [term]: [confirmed definition]
```

---

## Stop conditions during implementation

Stop and ask if you encounter:
- A contradiction with confirmed assumptions
- A new domain term not in `.epistemix/context.md`
- An architectural decision you cannot infer from the code

Do not guess. Do not assume. Ask.

---

## Project stack

{stack}

---

## Project conventions

{conventions}
"""


VERIFY_COMMAND_TEMPLATE = """\
Run the VERIFY protocol from CLAUDE.md for the task below.

Use Read, Grep and Glob to search the codebase before answering.
Also check .epistemix/context.md for existing priors and verification questions.

Do not guess — find evidence in files.

Task: $ARGUMENTS
"""


GITIGNORE_ENTRY = "\n# Epistemix runtime data\n.epistemix/\n"


def detect_stack(root: Path) -> str:
    """Auto-detect project stack from files present."""
    hints = []

    if (root / "package.json").exists():
        pkg = (root / "package.json").read_text(errors="ignore")
        if "next" in pkg.lower():
            hints.append("Next.js / TypeScript")
        elif "react" in pkg.lower():
            hints.append("React / TypeScript")
        else:
            hints.append("Node.js / JavaScript")

    if any(root.rglob("*.csproj")) or any(root.rglob("*.sln")):
        hints.append(".NET / C#")

    if any(root.rglob("*.py")) and (root / "pyproject.toml").exists():
        hints.append("Python")
    elif any(root.rglob("*.py")):
        hints.append("Python (scripts)")

    return ", ".join(hints) if hints else "Unknown — please fill in manually"


def setup_project(root: Path, force: bool = False) -> dict[str, bool]:
    """
    Set up Epistemix in a project directory.
    Returns a dict of what was created/skipped.
    """
    results = {}

    # .epistemix/ directory
    epistemix_dir = root / ".epistemix"
    epistemix_dir.mkdir(exist_ok=True)
    results["epistemix_dir"] = True

    # Placeholder context file
    context_path = epistemix_dir / "context.md"
    if not context_path.exists() or force:
        context_path.write_text(
            "# Epistemix context\n\n"
            "_Run `epistemix verify \"<task>\"` to populate this file._\n"
        )
        results["context"] = True
    else:
        results["context"] = False

    # .claude/commands/ directory
    commands_dir = root / ".claude" / "commands"
    commands_dir.mkdir(parents=True, exist_ok=True)

    # Slash command
    verify_cmd = commands_dir / "verify.md"
    if not verify_cmd.exists() or force:
        verify_cmd.write_text(VERIFY_COMMAND_TEMPLATE)
        results["slash_command"] = True
    else:
        results["slash_command"] = False

    # CLAUDE.md
    claude_md = root / "CLAUDE.md"
    if not claude_md.exists() or force:
        stack = detect_stack(root)
        claude_md.write_text(
            CLAUDE_MD_TEMPLATE.format(
                stack=f"- {stack}",
                conventions="_(fill in your naming conventions, architecture patterns, etc.)_"
            )
        )
        results["claude_md"] = True
    else:
        results["claude_md"] = False

    # .gitignore
    gitignore = root / ".gitignore"
    if gitignore.exists():
        content = gitignore.read_text()
        if ".epistemix" not in content:
            gitignore.write_text(content + GITIGNORE_ENTRY)
            results["gitignore"] = True
        else:
            results["gitignore"] = False
    else:
        gitignore.write_text(GITIGNORE_ENTRY.strip())
        results["gitignore"] = True

    return results
